### ISSUE TITLE
Any way to use py interpreter-specific coverage markers with pytest skip?

### ISSUE THREAD

**Issue by gaborbernat** [asottile/covdefaults#133]
I can do:

```python
if sys.version_info[:2] == (3, 10):  # pragma: ==3.10 cover # pytest.skip doesn't support covdefaults

    @pytest.mark.skipif(os.name != "posix", reason="POSIX 3.11+ specific")
    def test_fallback_existent_system_executable(mocker: MockerFixture) -> None:
        current = PythonInfo()
```

But I wonder if I can merge this check into the skipif?

**Comment by asottile** [comment]
that should work as you've written it -- you can also put it on the skip decorator itself

**Comment by gaborbernat** [comment]
Yeah the above works, but didn't manage to get it working when putting it in the skip decorator 🤔

**Comment by asottile** [comment]
show what you've tried?

**Comment by gaborbernat** [comment]
```python
    @pytest.mark.skipif(os.name == "posix" && sys.version_info[:2] == (3, 10) , reason="3.10 posix")
    def test_fallback_existent_system_executable(mocker: MockerFixture) -> None:  # pragma: ==3.10 cover # pragma: win32 no cover
        current = PythonInfo()
```

**Comment by asottile** [comment]
try putting it on the decorator itself?

**Comment by gaborbernat** [comment]
You should be able to combine these pragmas? Is there any way to specify or / and? Or for that use case, you're better off using if statements.

**Comment by gaborbernat** [comment]
> try putting it on the decorator itself?

Hm, this worked, but is a bit counterintuitive because for the if statement you put it after the `:`. Perhaps an example in the README of this would help future users. Thanks!

**Comment by asottile** [comment]
nice!

**Comment by gaborbernat** [comment]
> You should be able to combine these pragmas? Is there any way to specify or / and? Or for that use case, you're better off using if statements.

ping on this 😊

**Comment by asottile** [comment]
yes if you combine them as you've done then they both apply

**Comment by gaborbernat** [comment]
That would be an or and not an and combination no?

**Comment by asottile** [comment]
they're just excludes -- coverage considers them separately
