### ISSUE TITLE
Problematic `-> NoReturn` exclusion

### ISSUE THREAD

**Issue by webknjaz** [asottile/covdefaults#152]
The plugin has `-> ['"]?NoReturn['"]?:` in excludes. However, when I attempted integrating `covdefaults`, a co-maintainer pointed out that it's useful to measure coverage in functions that always raise exceptions (https://github.com/aio-libs/yarl/pull/1084#discussion_r1741265935). One example is `aiohttp`'s web response exceptions raised from HTTP handlers like https://github.com/aio-libs/aiohttp/blob/731ba4d/tests/test_client_functional.py#L1178-L1179.

@asottile could you document a justification for not measuring such cases? Any chance to have a way to remove this specific exclusion?

**Comment by asottile** [comment]
most `NoReturn` functions are unmeasurable (such as ones calling `os.execvp`)

**Comment by webknjaz** [comment]
@asottile I think that all of `NoReturn` functions I've ever seen are measurable, though. How to enable measuring them with `covdefaults` installed?

**Comment by asottile** [comment]
don't opt in to covdefaults if you don't want what it does? idk

**Comment by webknjaz** [comment]
I want all it does, except for this one thing. Can't there be an option to modify the defaults similar to `subtract_omit`? `substract_exclude_lines`?

**Comment by asottile** [comment]
idk if it's possible you'd have to research and implement it since generally I'm moving more to an open source stance of: I'm not going to build something I won't use

**Comment by webknjaz** [comment]
Just to clarify: are you saying the project doesn't want PRs either?

**Comment by asottile** [comment]
> you'd have to research and implement it

that sounds like a PR to me no?

**Comment by webknjaz** [comment]
It sounded like you didn't want to maintain any contributed code anymore. Accepting a PR includes reviewing, releasing, and maintaining new code, after all. So I had to ask. Maintaining a fork is also something I was considering if the divergence is too big.

Other than that, copying-and-pasting https://github.com/asottile/covdefaults/blob/77f9ff9/covdefaults.py#L121-L122 is something I could delegate to a mentee :man_shrugging:

Still, I need to check for one surprise incompatibility that popped up with PyPy to decide if it'll be possible to use the plugin even with that patch.

**Comment by asottile** [comment]
no what I meant is I'm not building random features for free any more
