### ISSUE TITLE
Unable to override report:skip_covered

### ISSUE THREAD

**Issue by amotl** [asottile/covdefaults#16]
Dear Anthony,

thanks a stack for conceiving and maintaining this excellent package.

Through https://github.com/daq-tools/wireviz-web/commit/042f04d0, we just added it to [wireviz-web](https://github.com/daq-tools/wireviz-web) and it works like a breeze. As we are using Poetry for package metadata, we store everything relevant within a `pyproject.toml` file. Now, we found that within this section
```toml
[tool.coverage.report]
fail_under = 90
skip_covered = false
```

overriding `fail_under` works, but overriding `skip_covered` apparently does not.

Maybe you can do anything about it?

With kind regards,
Andreas.

**Comment by asottile** [comment]
for booleans in coverage there isn't a way to know the difference between "the default is present as false" or "the user set the value to false"

could you elaborate on why you want `skip_covered = false`?  I understand it's desirable when making html / xml reports so I added an explicit `--no-skip-covered` option to coverage to facilitate that.  At the current time there's no way to configure that setting separately for different tasks

you'll want to consult / follow these (which will provide a potentially better solution):
- https://github.com/pytest-dev/pytest-cov/issues/449
- https://github.com/nedbat/coveragepy/issues/1090

**Comment by amotl** [comment]
Hi Anthony,

thanks for the quick reply. I understand the rationale much better now why it is not possible to override this flag, thanks.

>  I understand it's desirable when making html / xml reports so I added an explicit `--no-skip-covered` option to coverage to facilitate that.

I see, that will help. Thanks!

Just for the sake of completeness: Am I right to assume this option is **only** available for HTML/XML reports? I just tried to apply it to regular terminal output out of curiosity and it does not seem to be available there.

```bash
$ pytest --cov --no-skip-covered tests -vvv
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --no-skip-covered
  inifile: None
```

```bash
$ pytest --cov --cov-report=term:no-skip-covered tests -vvv
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --cov-report: output specifier not supported for: "term:no-skip-covered" (choose from "['annotate', 'html', 'xml']")
```

With kind regards,
Andreas.

**Comment by asottile** [comment]
`--no-skip-covered` is an option to `coverage` itself, I'm not sure what `pytest-cov` is doing there (I don't use it myself as I find it unnecessary) but if it's not passing along the option correctly that's probably their bug

**Comment by amotl** [comment]
I've just tried to give this a spin and it works great. Thank you so much for your help.
```
coverage run --source=wireviz_web $(which pytest) tests -vvvv && coverage report --no-skip-covered
```

P.S.: However, I've discovered a different problem with that but will open another issue in order not to pollute this one.

**Comment by asottile** [comment]
instead of `$(which pytest)` you can probably use `-mpytest` by the way

**Comment by amotl** [comment]
> Instead of `$(which pytest)` you can probably use `-mpytest` by the way.

That also works. Much better. Great!
```
coverage run --source=wireviz_web --module pytest tests -vvvv && coverage report --no-skip-covered
```

**Comment by amotl** [comment]
> P.S.: However, I've discovered a different problem with that but will open another issue in order not to pollute this one.

That was completely our fault, sorry - nothing to report here. I wish you happy new year and want to thank you again for your excellent support.
